# Generated by Django 2.2 on 2019-04-28 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=30)),
                ('bauthor', models.CharField(max_length=20)),
                ('bpublish_com', models.CharField(max_length=30)),
                ('bpublish_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('upwd', models.CharField(max_length=20)),
                ('ucollege', models.CharField(blank=True, max_length=20, null=True)),
                ('unum', models.CharField(blank=True, max_length=10)),
                ('uemail', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Histroys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hdate', models.DateTimeField(auto_now=True)),
                ('hreturn', models.DateTimeField()),
                ('hstatus', models.BooleanField(default=False)),
                ('hbookid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookgli.Books')),
                ('huserid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookgli.Users')),
            ],
        ),
    ]
